language: node_js
node_js:
  - 8
  - 10
  - 12

branches:
  except:
    - gh-pages

cache:
  yarn: true
  directories:
    - node_modules

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        - yarn lint
    - stage: test
      script:
        - yarn test:coverage
    - stage: build
      script:
        - yarn build
    - stage: build
      script:
        - yarn build
