language: node_js
node_js:
  - 12

branches:
  except:
    - gh-pages

cache:
  yarn: true

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        - yarn lint

    - stage: test
      node_js: 8
      script:
        - yarn test
    - stage: test
      node_js: 10
      script:
        - yarn test
    - stage: test
      node_js: 12
      script:
        - yarn test

    - stage: build
      name: build docs
      script:
        - yarn build:docs
    - stage: build
      name: build system
      script:
        - yarn build:system

after_success:
  - yarn global add codecov
  - codecov
