language: node_js
node_js:
  - 14

branches:
  except:
    - gh-pages

cache:
  yarn: true

stages:
  - lint
  - test
  - build

jobs:
  include:
    - stage: lint
      script:
        - yarn lint

    - stage: test
      node_js: 12
      script:
        - yarn test
    - stage: test
      node_js: 14
      script:
        - yarn test
    - stage: test
      node_js: 16
      script:
        - yarn test

    - stage: build
      name: build docs and system
      script:
        - yarn build:docs && yarn build:system

after_success:
  - yarn global add codecov
  - codecov
