image: node:8

pipelines:
  default:
    - step:
        max-time: 5
        caches:
          - node
        script:
          - yarn
          - TEST_REPORT_PATH=./test-reports/test-report.xml yarn test
