image: node:8

pipelines:
  default:
    - step:
        max-time: 5
        caches:
          - node
        script:
          - yarn
          - yarn lint
          - mkdir test-reports
          - TEST_REPORT_PATH=test-reports yarn test
