image: node:8

pipelines:
  default:
    - parallel:
      - step:
          name: Test
          max-time: 5
          caches:
            - node
          script:
            - yarn
            - yarn lint
            - mkdir test-reports
            - TEST_REPORT_PATH=test-reports yarn test
      - step:
          name: Audit
          max-time: 1
          script:
            - yarn audit
    # - step:
    #     name: Publish
    #     trigger: manual
    #     max-time: 5
    #     caches:
    #       - node
    #     script:
    #       - yarn
    #       - npm publish
